#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    --set=ON_ERROR_STOP=1 --set=password="$KRINE_POSTGRES_PASSWORD" <<'SQL'
CREATE ROLE krine LOGIN PASSWORD :'password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER DATABASE krine OWNER TO krine;
REVOKE ALL ON DATABASE krine FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO krine;
SQL
unset KRINE_POSTGRES_PASSWORD
